# Generated by Django 5.1.6 on 2025-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.JSONField(default=list)),
                ('address', models.CharField(max_length=255)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('reserved', 'Забронировано'), ('rented', 'Сдано')], default='available', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rooms', models.PositiveIntegerField()),
                ('floor_current', models.PositiveIntegerField()),
                ('floor_full', models.PositiveIntegerField()),
                ('bath', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('fireplace', models.BooleanField(default=False)),
                ('beautiful_view', models.BooleanField(default=False)),
                ('new_building', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.JSONField(default=list)),
                ('address', models.CharField(max_length=255)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('reserved', 'Забронировано'), ('rented', 'Сдано')], default='available', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_agricultural', models.BooleanField(default=False)),
                ('has_communications', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.JSONField(default=list)),
                ('address', models.CharField(max_length=255)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('reserved', 'Забронировано'), ('rented', 'Сдано')], default='available', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('floor', models.PositiveIntegerField()),
                ('open_space', models.BooleanField(default=False)),
                ('meeting_rooms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
