# Generated by Django 5.1.6 on 2025-06-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.JSONField(default=list)),
                ('address', models.CharField(max_length=255)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('rented', 'Rented')], default='available', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor_current', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_full', models.PositiveIntegerField(blank=True, null=True)),
                ('bath', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('fireplace', models.BooleanField(default=False)),
                ('beautiful_view', models.BooleanField(default=False)),
                ('new_building', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('kitchen_type', models.CharField(blank=True, max_length=50, null=True)),
                ('renovation', models.CharField(blank=True, max_length=50, null=True)),
                ('furnished', models.CharField(blank=True, max_length=50, null=True)),
                ('shared_kitchen', models.BooleanField(default=False)),
                ('shared_bathroom', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=False)),
                ('has_gas', models.BooleanField(default=False)),
                ('has_sewerage', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='contacts.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.JSONField(default=list)),
                ('address', models.CharField(max_length=255)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('rented', 'Rented')], default='available', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_agricultural', models.BooleanField(default=False)),
                ('has_communications', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landlots', to='contacts.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.JSONField(default=list)),
                ('address', models.CharField(max_length=255)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('rented', 'Rented')], default='available', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('floor', models.PositiveIntegerField()),
                ('open_space', models.BooleanField(default=False)),
                ('meeting_rooms', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='contacts.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
