# Generated by Django 5.1.6 on 2025-07-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.JSONField(default=dict),
        ),
    ]
