# Generated by Django 5.1.6 on 2025-04-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='floor_current',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor_full',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
