# Generated by Django 5.1.6 on 2025-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_flat_deleted_at_flat_is_deleted_landplot_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='furnished',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='has_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='has_gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='has_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='has_sewerage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='has_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='kitchen_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='renovation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='shared_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='shared_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
