# Generated by Django 5.1.6 on 2025-07-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_flat_address_alter_landplot_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='map_link',
        ),
        migrations.RemoveField(
            model_name='landplot',
            name='map_link',
        ),
        migrations.RemoveField(
            model_name='office',
            name='map_link',
        ),
    ]
