# Generated by Django 5.1.6 on 2025-07-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_flat_map_link_remove_landplot_map_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='has_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='heating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.JSONField(),
        ),
    ]
