# Generated by Django 5.1.6 on 2026-03-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='air_conditioning',
        ),
        migrations.RemoveField(
            model_name='land',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='land',
            name='bath',
        ),
        migrations.RemoveField(
            model_name='land',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='land',
            name='fireplace',
        ),
        migrations.RemoveField(
            model_name='land',
            name='floor_current',
        ),
        migrations.RemoveField(
            model_name='land',
            name='floor_full',
        ),
        migrations.RemoveField(
            model_name='land',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='land',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='land',
            name='kitchen_type',
        ),
        migrations.RemoveField(
            model_name='land',
            name='new_building',
        ),
        migrations.RemoveField(
            model_name='land',
            name='renovation',
        ),
        migrations.RemoveField(
            model_name='land',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='land',
            name='shared_bathroom',
        ),
        migrations.RemoveField(
            model_name='land',
            name='shared_kitchen',
        ),
        migrations.RemoveField(
            model_name='land',
            name='shower',
        ),
    ]
