# Generated by Django 5.1.6 on 2025-07-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_flat_balcony_flat_garage_flat_garden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='has_electricity',
            new_name='electricity',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='has_gas',
            new_name='internet',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='has_heating',
            new_name='natural_gas',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='has_internet',
            new_name='sewerage',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='has_sewerage',
            new_name='water_supply',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='has_water',
        ),
    ]
