# Generated by Django 5.1.6 on 2025-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_has_electricity_flat_electricity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='zoning_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
