# Generated by Django 5.1.6 on 2025-11-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_flat_airconditioning'),
        ('contacts', '0002_contact_additional_phone_contact_dateadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='contact',
        ),
        migrations.AlterField(
            model_name='flat',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='contacts.contact'),
        ),
        migrations.DeleteModel(
            name='LandPlot',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
