services:
  frontend: #FRONTEND
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - backend  
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=testdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  postgres: # DATABASE
    image: postgres:16
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data  # Сохранение данных
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis: # REDIS
    image: redis:latest
    container_name: realtor_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: