# Generated by Django 5.1.6 on 2025-11-07 17:45

import file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=file.models.temp_upload_path),
        ),
    ]
