# Generated by Django 5.1.6 on 2025-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_additional_phone_contact_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
