# Generated by Django 5.1.6 on 2025-03-01 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='insertedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 2, 1, 22, 58, 512855)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
