# Generated by Django 5.1.6 on 2025-11-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='propoerty_object_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='public_link',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
