# Generated by Django 5.1.6 on 2025-11-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_company_logo_listing_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='propoerty_object_ids',
        ),
        migrations.AddField(
            model_name='listing',
            name='property_object_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
