# Generated by Django 5.1.6 on 2025-12-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='created_at',
            new_name='date_added',
        ),
    ]
