# Generated by Django 5.1.6 on 2026-03-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_marketing_consent1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_consent1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_consent2',
            field=models.BooleanField(default=True),
        ),
    ]
