# Generated by Django 5.1.6 on 2026-01-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
