# Generated by Django 5.1.6 on 2026-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_logout_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='insertedAt',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
