# Generated by Django 5.1.6 on 2026-03-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_default_country_user_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_country',
            field=models.CharField(blank=True, default='Null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.CharField(blank=True, default='Null', max_length=255, null=True),
        ),
    ]
