# Generated by Django 5.1.6 on 2026-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_default_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
